### ISSUE TITLE
Usage?

### ISSUE THREAD

**Issue by gurpal2000** [tobes/MorningScraper#2]
How do you actually use this on the command line? Commands?

**Comment by marfeljoergsen** [comment]
I don't think this is working. I think the idea is that you should just do: "import morningscraper as m", but then it fails miserably:

In [8]: test=m.search('GB00B54RK123',verbose=False)
/usr/lib/python3.9/site-packages/morningscraper/__init__.py:67: GuessedAtParserWarning: No parser was explicitly specified, so I'm using the best available HTML parser for this system ("lxml"). This usually isn't a problem, but if you run this code on another system, or in a different virtual environment, it may use a different parser and behave differently.

The code that caused this warning is on line 67 of the file /usr/lib/python3.9/site-packages/morningscraper/__init__.py. To get rid of this warning, pass the additional argument 'features="lxml"' to the BeautifulSoup constructor.

  parsed_html = BeautifulSoup(data)

In [9]: test
Out[9]: []

So it returns no data. I also don't see the author is replying or has done anything in the past years. I think this project is abandoned, unfortunately.

**Comment by gurpal2000** [comment]
@marfeljoergsen thank you for your detailed reply. I think it is sadly as you say...
